name: mdns_plugin_example
description: Demonstrates how to use the mdns_plugin plugin.
version: 1.1.1
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mdns_plugin:
    path: ../

flutter:
  uses-material-design: true
